---
# handlers file for provision_proxmox_vms
- name: firewalld gt rhel7
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: yes 
  become: true
  when: 
    - ansible_distribution_major_version|int > 7

- name: firewalld eq rhel7
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes 
  become: true
  when: 
    - ansible_distribution_major_version|int == 7