---
- hosts: "{{ target }}"
  gather_facts: True
  become: True
  vars:
    redhat_user: "{{ lookup('env','REDHAT_USER') }}"
    redhat_pass: "{{ lookup('env','REDHAT_PASS') }}"
  tasks:
    - ansible.builtin.assert:
        that:
          - redhat_user is defined 
          - redhat_pass is defined 
          - redhat_user|length > 0
          - redhat_pass|length > 0

    - meta: end_host
      when: 
        - ansible_distribution is defined 
        - ansible_distribution|lower != "redhat"

    - name: Register to Red Hat for subscriptions and auto-subscribe to available content.
      community.general.redhat_subscription:
          state: present
          username: "{{ redhat_user }}"
          password: "{{ redhat_pass }}"
          auto_attach: true

    - name: install packages for language locale
      yum:
        name:
          - glibc-langpack-en
      when:
          - ansible_distribution_major_version|int >= 8

    - name: Update packages
      yum:
        name: '*'
        state: latest

    - name: Check if server needs rebooting
      ansible.builtin.shell: /usr/bin/needs-restarting -r
      failed_when: false
      register: __reboot_required

    - name: Reboot server
      ansible.builtin.reboot:
      when: __reboot_required['rc']|int == 1           

    