---
- hosts: virtual_machines
  gather_facts: false
  collections:
       community.general
  pre_tasks:
     - name: Assert that vars required for lookup exist
       ansible.builtin.assert:
          that:
            - cloud_init_user is defined
            - cloud_init_pass is defined
            - cloud_init_public_key is defined
            - proxmox_api_host is defined 
            - proxmox_api_user is defined 
            - proxmox_api_pass is defined 
            - redhat_user is defined 
            - redhat_pass is defined 
            - cloud_init_user|length > 0
            - cloud_init_pass|length > 0
            - cloud_init_public_key|length > 0
            - proxmox_api_host|length > 0
            - proxmox_api_user|length > 0
            - proxmox_api_pass|length > 0
            - redhat_user|length > 0
            - redhat_pass|length > 0
       tags:
         - always
 

     - name: Ensure netaddr python module is installed if not in a virtual environment
       ansible.builtin.pip:
           name: netaddr
           extra_args: "{{ omit if lookup('env','VIRTUAL_ENV') is defined  else '--user' }}"
       delegate_to: localhost
       run_once: True

  roles:
     - provision_proxmox_vms


    
