# ---
# plugin: community.general.proxmox
# validate_certs: false
# url: "https://proxmox3.example.com:8006" <- Use your proxmox node name here
# user: "{{ lookup('env','PROXMOX_USER') }}"
# password: "{{ lookup('env','PROXMOX_PASSWORD') }}"
# cache: no
# cache_timeout: 1
# want_proxmox_nodes_ansible_host: false
# want_facts: true
# keyed_groups:
#    - key: proxmox_tags_parsed
# groups:
#     aap_servers: "'aap' in (proxmox_tags_parsed|list)"
#     ansible_servers: "'ansible' in (proxmox_tags_parsed|list)"
#     controller_servers: "'controller' in (proxmox_tags_parsed|list)"
#     dns_servers: "'dns' in (proxmox_tags_parsed|list)"
#     rhel7_servers: "'rhel7' in (proxmox_tags_parsed|list)"
#     rhel8_servers: "'rhel8' in (proxmox_tags_parsed|list)"
#     rhel9_servers: "'rhel9' in (proxmox_tags_parsed|list)"
#     rhel_servers: "'rhel' in (proxmox_tags_parsed|list)"
#     satellite_servers: "'satellite' in (proxmox_tags_parsed|list)"
# compose:
#     ansible_ssh_private_key_file: '~/.ssh/id_rsa_proxmox'
#     ansible_host: proxmox_agent_interfaces[1].ip-addresses[0]|ansible.utils.ipaddr('address')
#     ansible_port: ansible_host: proxmox_agent_interfaces[1].ip-addresses[0]|ansible.netcommon.ipaddr('address')
#     onefish: "'redfish'"  <- This creates a hostvar called onefish with a value of redfish
#     twofish: "'bluefish'"  <- This creates a hostvar called twofish with a value of bluefish
#     greeneggs: "'ham'" <- This creates a hostvar called greeneggs with a value of ham