# THIS IS AN EXAMPLE DYNAMIC INVENTORY FILE THAT CAN BE UNCOMMENTED, MODIFIED, AND
# USED AT YOUR DISCRETION. YMMV
# SEE: https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_inventory.html
# 
# ---
# plugin: community.general.proxmox
# validate_certs: false
# url: "https://{{ lookup('env','PROXMOX_HOST') }}:8006"
# user: "{{ lookup('env','PROXMOX_USER') }}"
# password: "{{ lookup('env','PROXMOX_PASSWORD') }}"
# want_proxmox_nodes_ansible_host: false
# want_facts: 'true'
# THE PREFIX IS UNNEEDED FOR ME, BUT IN YOUR USE CASE
# YOU MAY WANT TO APPLY ONE. USING IT WILL CREATE A
# NAME WITH THE PREFIX.  ALL DYNAMICALLY FOUND GROUPS
# GET PREPENDED WITH IT.
# keyed_groups:
#    - key: proxmox_tags_parsed
#      prefix: foo

# YOU CAN CREATE GROUPS BASED ON VM TAGS WITH THIS
# INVENTORY
# groups:
#     rhel9: "'rhel9' in (proxmox_tags_parsed|list)"
#     rhel8: "'rhel8' in (proxmox_tags_parsed|list)"
#     rhel7: "'rhel7' in (proxmox_tags_parsed|list)"
#     rhelservers: "'rhel' in (proxmox_tags_parsed|list)"
# compose:
#     ansible_port: 22
