---
plugin: community.general.proxmox
validate_certs: false
url: "https://{{ lookup('env','PROXMOX_HOST') }}:8006"
user: "{{ lookup('env','PROXMOX_USER') }}"
password: "{{ lookup('env','PROXMOX_PASSWORD') }}"
want_proxmox_nodes_ansible_host: false
want_facts: 'true'
keyed_groups:
   - key: proxmox_tags_parsed
     separator: ""
#    prefix: group <-unneeded
groups:
    rhel9: "'rhel9' in (proxmox_tags_parsed|list)"
    rhel8: "'rhel8' in (proxmox_tags_parsed|list)"
    rhel7: "'rhel7' in (proxmox_tags_parsed|list)"
    rhelservers: "'rhel' in (proxmox_tags_parsed|list)"
compose:
    ansible_port: 22
