---
plugin: community.general.proxmox
validate_certs: false
password: "{{ proxmox_api_pass }}"
user: "{{ proxmox_api_user }}"
url: "https://{{ proxmox_api_host }}:8006"
want_proxmox_nodes_ansible_host: false
want_facts: 'true'
keyed_groups:
   - key: proxmox_tags_parsed
     separator: ""
#    prefix: group <-unneeded
groups:
    rhel9: "'rhel9' in (proxmox_tags_parsed|list)"
    rhel8: "'rhel8' in (proxmox_tags_parsed|list)"
    rhel7: "'rhel7' in (proxmox_tags_parsed|list)"
    rhelservers: "'rhel' in (proxmox_tags_parsed|list)"
compose:
    ansible_port: 22
