---
# defaults file for provision_proxmox_vms
ciuser: "{{ cloud_init_user| default(lookup('env','CLOUD_INIT_USERNAME')) }}"
cipassword: "{{ cloud_init_password | default(lookup('env','CLOUD_INIT_PASSWORD')) }}"
cipublickey: "{{ cloud_init_public_key | default(lookup('env','CLOUD_INIT_PUBLIC_KEY')) }}"

proxmox_api_host: "{{ lookup('env','PROXMOX_HOST') }}"
proxmox_api_pass: "{{ lookup('env','PROXMOX_PASSWORD') }}"
proxmox_api_user: "{{ lookup('env','PROXMOX_USER') }}"

redhat_username: "{{ lookup('env','REDHAT_SSO_USERNAME') }}"
redhat_password: "{{ lookup('env','REDHAT_SSO_PASSWORD') }}"

qcow_image_path: /opt/qcow_images/images

qcow_images:

  - name: rhel7
    qcow_file: rhel-server-7.9-update-12-x86_64-kvm.qcow2

  - name: rhel8
    qcow_file: rhel-8.8-x86_64-kvm.qcow2

  - name: rhel9
    qcow_file: rhel-9.2-x86_64-kvm.qcow2

  - name: ubuntu18
    qcow_file: bionic-server-cloudimg-amd64.qcow2

  - name: ubuntu20
    qcow_file: focal-server-cloudimg-amd64.qcow2


virtual_machine_nameservers:
  - 192.168.1.100
  - 192.168.1.200
